# Generated by Django 3.1.4 on 2020-12-25 03:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201223_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', ckeditor.fields.RichTextField()),
                ('answer', ckeditor.fields.RichTextField(blank=True)),
                ('Test', models.TextField(blank=True)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
            ],
        ),
    ]
