# Generated by Django 3.1.4 on 2020-12-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_practicequestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicequestions',
            old_name='courseName',
            new_name='course',
        ),
    ]
