# Generated by Django 3.1.4 on 2021-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201224_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestions',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
