# Generated by Django 3.1.4 on 2021-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_practicequestions_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
