# Generated by Django 3.1.4 on 2021-01-28 18:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210128_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
