# Generated by Django 3.1.4 on 2021-04-07 21:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210128_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
